<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
    <!--[if IE ]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title><?=$this->title?> - PHP Framework</title>
    <?=$this->includeCss();?>
    <?=$this->includeJs();?>

</head>
	<body>
		<div style="margin:0 auto; margin-top:150px; width:500px; text-align:center; font-family:Verdana;">
			<span style="font-size:35px;">Play Bongos!</span>
			<img src="/public/images/bongo.jpg">
		</div>

		<?$this->render();?>

	</body>
</html>
